# Muertes Mundiales

## Fuente: Kaggle

In [ ]:
pip install couchdb

In [1]:
#Librerias
import csv
import couchdb
import pandas as pd

In [2]:
# Leer archivo csv
dfcouchdb1 = pd.read_csv('cause_of_deaths.csv', encoding='utf-8')

In [3]:
#Impresion del dataframe
dfcouchdb1

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,2231,3932,451,3038,6001,6664,3027,5739,420,3816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6115,Zimbabwe,ZWE,2015,1439,754,215,3019,2518,770,1302,...,3176,2108,381,2990,2373,2751,1956,4202,632,146
6116,Zimbabwe,ZWE,2016,1457,767,219,3056,2050,801,1342,...,3259,2160,393,3027,2436,2788,1962,4264,648,146
6117,Zimbabwe,ZWE,2017,1460,781,223,2990,2116,818,1363,...,3313,2196,398,2962,2473,2818,2007,4342,654,144
6118,Zimbabwe,ZWE,2018,1450,795,227,2918,2088,825,1396,...,3381,2240,400,2890,2509,2849,2030,4377,657,139
6119,Zimbabwe,ZWE,2019,1450,812,232,2884,2068,827,1434,...,3460,2292,405,2855,2554,2891,2065,4437,662,136

In [4]:
#Contabilizar datos nulos
dfcouchdb1.isnull().sum()

Country/Territory                             0
Code                                          0
Year                                          0
Meningitis                                    0
Alzheimer's Disease and Other Dementias       0
Parkinson's Disease                           0
Nutritional Deficiencies                      0
Malaria                                       0
Drowning                                      0
Interpersonal Violence                        0
Maternal Disorders                            0
HIV/AIDS                                      0
Drug Use Disorders                            0
Tuberculosis                                  0
Cardiovascular Diseases                       0
Lower Respiratory Infections                  0
Neonatal Disorders                            0
Alcohol Use Disorders                         0
Self-harm                                     0
Exposure to Forces of Nature                  0
Diarrheal Diseases                            0
Environmental Heat and Cold Exposure          0
Neoplasms                                     0
Conflict and Terrorism                        0
Diabetes Mellitus                             0
Chronic Kidney Disease                        0
Poisonings                                    0
Protein-Energy Malnutrition                   0
Road Injuries                                 0
Chronic Respiratory Diseases                  0
Cirrhosis and Other Chronic Liver Diseases    0
Digestive Diseases                            0
Fire, Heat, and Hot Substances                0
Acute Hepatitis                               0
dtype: int64

In [6]:
#Convertir el dataframe en un diccionario
datoscouchdb1 = dfcouchdb1.to_dict(orient='records')

#Conexion couchdb
servidorcouchdb1 = couchdb.Server('http://admin:admin@localhost:5984/')
dbcouchdb1 = servidorcouchdb1['muertes_mundiales1']

#Ingresar los datos en la base de datos
for documento in datoscouchdb1:
    dbcouchdb1.save(documento)

## Fuente: Repositorio GitHub

In [ ]:
#Librerias
import csv
import couchdb
import pandas as pd

In [7]:
# Leer archivo csv
dfcouchdb2 = pd.read_csv('world_mortality.csv', encoding='utf-8')

In [8]:
#Impresion del dataframe
dfcouchdb2

      iso3c country_name  year  time time_unit  deaths
0       ALB      Albania  2015     1   monthly    2490
1       ALB      Albania  2015     2   monthly    2139
2       ALB      Albania  2015     3   monthly    2051
3       ALB      Albania  2015     4   monthly    1906
4       ALB      Albania  2015     5   monthly    1709
...     ...          ...   ...   ...       ...     ...
27454   UZB   Uzbekistan  2022     8   monthly   18771
27455   UZB   Uzbekistan  2022     9   monthly   13351
27456   UZB   Uzbekistan  2022    10   monthly   13602
27457   UZB   Uzbekistan  2022    11   monthly   12850
27458   UZB   Uzbekistan  2022    12   monthly   15395

[27459 rows x 6 columns]

In [9]:
#Contabilizar datos nulos
dfcouchdb2.isnull().sum()

iso3c           0
country_name    0
year            0
time            0
time_unit       0
deaths          0
dtype: int64

In [10]:
#Convertir el dataframe en un diccionario
datoscouchdb2 = dfcouchdb2.to_dict(orient='records')

#Conexion couchdb
servidorcouchdb2 = couchdb.Server('http://admin:admin@localhost:5984/')
dbcouchdb2 = servidorcouchdb2['muertes_mundiales2']

#Ingresar los datos en la base de datos
for documento in datoscouchdb2:
    dbcouchdb2.save(documento)